project:
  type: website
  resources: 
    - "data/"
    - "files/"

website:
  page-navigation: true
  title: "Stat 340"
  description: "Homepage for Stat 340 - Bayesian Statistics at Carleton College, Fall 2025."

  repo-url: https://github.com/aluby/stat340-f25

  sidebar:
    background: "#E2583E" # Pantone tigerlily
    logo: "images/bayes-logo.png"
    pinned: true
    align: center
    tools:
      - icon: code-square
        href: https://maize.mathcs.carleton.edu/
        text: "RStudio Server"
      - icon: person-fill
        href: https://moodle.carleton.edu/course/view.php?id=47069
        text: "Moodle"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - text: "Syllabus"
        href: course-syllabus.qmd
      - text: "Schedule"
        href: index.qmd
      - section: "Computing"
        contents:
          - href: computing/computing-setup.qmd
            text: Setup
          - href: computing/rstudio-stat340.qmd
            text: Rstudio in Stat 340
          - href: computing/r-basics-refresher.qmd
            text: R Refresher
          - href: https://r-primers.andrewheiss.com/
            text: R Primers for more practice
          - href: computing/computing-cheatsheets.qmd
            text: Cheatsheets
      - section: "Assignments"
        contents: 
          - auto: homework/
          - auto: groupwork/
      - section: "Projects"
        contents: projects/
          
  page-footer:
    right: "This page is built with ☕️ and [Quarto](https://quarto.org/)."
    left: "Material 2025, Amanda Luby <br> Design by Mine Çetinkaya-Rundel"
    background: "#E2583E" # Pantone Tigerlily
    
format:
  html:
    theme:
      light: [cosmo, style/stat340.scss]
      dark: [cosmo, style/stat340.scss, style/dark.scss]
    linkcolor: "#866fa3" # Glossy Grape
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-light
    code-link: true

execute:
  freeze: auto

editor: source
