---
title: "Stat340: Bayesian Statistics"
subtitle: "Fall 2025"
execute:
  freeze: true
typst-logo:
  path: "logo.png"
format: 
  html: default
  syllabus-typst: default
---


::: {.boxed-text}
+----------------+-------------------------------------------------------------+------------------+
| MEETINGS:      | MWF 3a                                                      | CMC 306          |
|                |                                                             |                  |
|                | 11:10-12:20 MW; 12-1 F                                      |                  |
+----------------+-------------------------------------------------------------+------------------+
| PROFESSOR:     | Amanda Luby                                                 | CMC 223          |
|                |                                                             |                  |
|                | aluby\@carleton                                             |                  |
+----------------+-------------------------------------------------------------+------------------+
| DROP-IN HOURS: | Mon 12:30-1:30                                              | CMC 307          |
|                |                                                             |                  |
|                | Tues 2-3                                                    |                  |
|                |                                                             |                  |
|                | Wed 3-4 (120 priority)                                      |                  |
|                |                                                             |                  |
|                | Fri 10-11 (340 priority)                                    |                  |
+----------------+-------------------------------------------------------------+------------------+
| WEBSITE:       | moodle.carleton.edu                                         |                  |
|                |                                                             |                  |
|                | aluby.github.io/stat340-s25                                 |                  |
+----------------+-------------------------------------------------------------+------------------+
| TEXT:          | *Bayes Rules! An Introduction to Applied Bayesian Modeling* |                  |
+----------------+-------------------------------------------------------------+------------------+
| SOFTWARE       | R: free download from r-project.org/                        |                  |
|                |                                                             |                  |
|                | RStudio: free download from rstudio.com/downloads           |                  |
|                |                                                             |                  |
|                | {rstan}: R package for MCMC sampling                        |                  |
+----------------+-------------------------------------------------------------+------------------+

: {tbl-colwidths="\[25,50,25\]"}
:::

```{=typst}
#colbreak()
```

# Course Description

When you analyze data about weather patterns in Minnesota, effectiveness of different teaching methods, or whether someone is likely to use the word “soda” or “pop”, you’re likely bringing your own experiences and knowledge into your statistical analyses and conclusions. This knowledge often gives you a “gut check” of whether your results are reasonable. What if we could incorporate that knowledge and experience formally into our statistical models? In Bayesian Statistics, we'll explore how to formulate our prior knowledge into probability distributions, how data helps us refine these beliefs into posterior distributions, and how these distributions can be used to make informed decisions and quantify uncertainty. We'll revisit linear and logistic regression models from Stat230, and learn how to adapt them and build “artisanal” Bayesian models for unique situations. We'll also tackle the crucial questions of how to assess if our Bayesian models are a good fit for the data and how to use them to make predictions with honest estimates of uncertainty. We'll focus on hands-on data analysis using modern Bayesian modeling packages in R, bringing these powerful techniques to life with real-world examples. Get ready to move beyond p-values and coverage-based intervals and embrace a richer understanding of the probabilities and uncertainties that underlie the stories our data tells!

# Course Objectives

After completing this course, you should be be able to demonstrate your competency with:

-   Explaining the differences between frequentist and Bayesian approaches to statistics and data analysis
-   Selecting appropriate prior distributions and likelihood models for Bayesian analysis
-   Using modern software to fit Bayesian models and assess their performance
-   Interpreting results from Bayesian analyses

# Course Components

## Meetings

There will be three course meetings per week (Mondays, Wednesdays, and Fridays). Daily attendance and active participation is expected. Course meetings will combine demonstrations/lecture and in-class group exercises. Each course day has an associated reading from the textbook. I expect you to complete the reading before class, and returning to the textbook afterwards if you have any lingering confusion about the material from the day.

## Individual Assignments

Individual homework will be assigned once-ish per week, typically due on Fridays at the beginning of class. You will submit homework assignments via gradescope. You will use {quarto} for all assignments. Individual assignments will be graded on completion.

## Group Assignments

Each course day, you'll be assigned a few problems as "group homework". On the day homework is due (typically Fridays), you'll submit solutions to these problems as a group via gradescope. Group assignments will be graded on correctness and completion.

## Homework quizzes

On days that homework is due, we will begin class with a short "homework quiz". I will ask you 1-2 questions that are based entirely on the homework you just submitted. These will be graded on correctness, and your lowest score will be dropped.

## Exams

There will be two in-class exams, tentatively scheduled for Fridays of Week 4 and 8.

## Projects

There will be two projects (one midterm project and one final project). You will work in groups of 2-3 for each project.

# Grading Policies

Grades are an imperfect measure of learning, and no grading scheme will perfectly capture your "true" learning in this course. This grading scheme is designed to reward you for consistently participating, staying on top of the course material, and demonstrating proficiency with the content through in-class assessments.

Final grades will be calculated as follows:

-   30% Homework
    - 10% Individual 
    - 10% Group 
    - 10% Homework quizzes
-   10% Midterm project + presentation
-   20% Final project + presentation
-   20% Exam I
-   20% Exam II

And letter grades will be assigned based on the usual grading scale (A = 93% and above, A- = 90-92.9%, B+ = 88-89.9%, B = 83-87.9%, etc.).

*A note on the "genius myth"*: I’ve found that many carls buy into the “genius myth” when it comes to math/stat courses: that you need to be a “math person” and have some innate mathematical ability in order to do well. This could not be further from the truth! The best statisticians don’t necessarily have the “best” math or programming background, but are people that are able to formulate interesting questions and use math and programming to answer those questions. Many of the best statisticians I know became statisticians because they were initially interested in something else (biology, public health, psychology, neuroscience, physics, etc.) and realized that being able to answer important questions with data was not only valuable but fun and interesting. Being able to perform interesting statistical analyses is a skill that is learned, not an innate ability, and working hard at developing that skill is the point of this course.

## Regrade requests

Grading is often a tedious task, and the grading team will sometimes make mistakes. I am always happy to fix these mistakes, and gradescope makes it easy to do so. Regrade requests must be submitted on gradescope within two weekdays after an assignment or exam has been returned to you. Regrade requests are for administrative errors or obvious grading mistakes. I will not consider regrade requests for anything that applied to the entire class (e.g. “I think this mistake should only be worth 1 point instead of 2” or “I didn’t realize we had to do X”). If you submit two or more inappropriate regrade requests, I will not consider additional regrade requests from you for the remainder of the term. If you’re unsure whether you should file a regrade request or not, just ask! You are always welcome to discuss any grading questions with me in office hours.

## Exam revisions

I offer the opportunity to submit exam revisions for two reasons: (1) to correct any major misunderstandings and have a chance to revisit material that you struggled with, (2) to mitigate the impact that a bad exam day can have on your final course grade. You can submit corrections to your exam to earn back 50% of your missed points. Corrected exam grades are capped at 80%. Exam revisions are due 1 week after graded exams are returned to you, or the last day of class at 11:59pm, whichever is earlier.

## Missing homework quizzes and exams

If you miss a class when there is an exam or homework quiz and don’t make arrangements with me at least a week in advance, then there are no makeups offered. If must miss an exam due to an illness or other last minute emergency, please let me know in advance to arrange an alternative. There are no makeup homework quizzes. 

# Materials

## Textbook

Our textbook is freely available online:

-   *Bayes Rules! An Introduction to Applied Bayesian Mdoeling* <https://www.bayesrulesbook.com/>

If you prefer a hard copy, they are also available for purchase through the bookstore and/or publisher.

I may also periodically assign or recommend readings from other sources. These will either be freely available online or I will provide a PDF. If you require readings in another format, please let me know during the first week of class.

## Software

The use of the [R](https://cran.rstudio.com/) programming language, with the [RStudio](https://posit.co/download/rstudio-desktop/) interface is an essential component of this course. Bayesian Statistics is more computationally intense than traditional frequentist methods, and so you will need to install local versions of the software on your own computer, or plan to complete assignments on a lab computer.

# Academic Integrity

You are expected to follow Carleton’s [policies regarding academic integrity](https://www.carleton.edu/handbook/academics/?policy=329). I encourage you to discuss the homework problems with others and use the resources available to you to try to figure out tough problems. You should code and write up your solutions on your own. Exams must be done by yourself without communicating with others; all work must be your own. You should collaborate with your teammates on projects, and should use external resources for background research and debugging, but all work should be original and all sources should be properly cited. The use of textbook solution manuals (physical or online), course materials from other students, or materials from previous versions of this course are not allowed.

Large-language models (e.g. ChatGPT, Gemini, etc.) should only be used for coding or debugging help after you’ve attempted to solve the problem on your own, and you should never type homework problems directly into a prompt. Copying, paraphrasing, summarizing, or submitting work generated by anyone but yourself without proper attribution is considered academic dishonesty (this includes output from LLMs).

I also have a few rules in place to protect my intellectual property. You may not record my lectures using tools such as Otter.ai or upload any video or audio recordings to generate transcripts or study notes. You may not upload my course materials (slides, assignment prompts, note sets, etc.) into AI tools or homework help sites (such as chegg).

“AI” tools are new for all of us and it’s OK to have questions about what is and isn’t appropriate. Please ask if you are unsure of whether or not your actions are complying with the assignment/quiz/project instructions. Always default to acknowledging any help received. Cases of suspected academic dishonesty are handled by the Provost’s Office and I am obligated to report any suspected violations of this policy.

# Diversity and Inclusion

We all come to class with different backgrounds and experiences, and this diversity makes our class environment richer. I value diversity and inclusion, and am committed to a climate of mutual respect and full participation in and out of the classroom. This class strives to be a learning environment that is usable, equitable, inclusive and welcoming, regardless of race, ethnicity, religion, gender and gender identities, sexual orientation, ability, socioeconomic background, and nationality. If you anticipate or experience any barriers to learning, please discuss your concerns with me.

# Resources

## Communication

Assignments and slides will be shared publicly on our course website. Grades will be posted on gradescope and/or Moodle. Please use our slack workspace for any homework or course content questions; email me privately with any personal matters (grade discussions, illness, emergency, etc.). Any time-sensitive announcements will be sent via email. It is your responsibility to make sure that your notification settings allow time-sensitive announcements to reach you.

## Professor availability

Please reach out to me if you have any questions! You can reach me on slack, email, drop-in hours, or make an appointment. Slack is typically the best venue for homework/content questions outside of drop-in hours. I’ll respond to slack messages at least 3 times each week day, and try to respond to emails within 48 hours You will receive responses faster on slack than email. I am online irregularly over the weekend to devote time to family and rest, and I hope that you also find time over the weekend to recharge and reset!

## Accomodations

Carleton College is committed to providing equitable access to learning opportunities for all students. The Office of Accessibility Resources (Henry House, 107 Union Street) is the campus office that collaborates with students who have disabilities to provide and/or arrange reasonable accommodations. If you have, or think you may have, a disability, please contact OAR\@carleton.edu to arrange a confidential discussion regarding equitable access and reasonable accommodations. You are also welcome to contact me privately to discuss your academic needs. However, all disability-related accommodations must be arranged, in advance, through OAR.

## Title IX

Please be aware that all faculty are “responsible employees”, which means that if you tell me about a situation involving sexual harassment, sexual assault, dating violence, domestic violence, or stalking, I must share that information with the Title IX Coordinator. Although I have to make this notification, you will control how your case will be handled, including whether or not you wish to meet with the Title IX coordinator or pursue a formal complaint.

## Take care of yourself

Do your best to maintain a healthy lifestyle this term by wearing a mask when you’re sick, eating a vegetable every now and then, exercising, avoiding excessive drug and alcohol use, getting enough sleep, and taking some time to relax. Your physical and mental health is more important than your grade in this course. There are many helpful resources available on campus and an important part of the college experience is learning how to ask for help. For more information, see Student Health and Counseling (SHAC), the Office of Health Promotion, or the Office of the Chaplain. If you are experiencing physical or mental health symptoms as a result of coursework, please speak with me so we can address the problem together.
